- name : catalogue
  hosts: catalogue
  become: yes
  tasks:
   - name: Disable Old Version and Enable Specfic Version
     ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
   - name: Install Mongodb
     ansible.builtin.package:
        name: nodejs
        state: present
   - name: create User
     ansible.builtin.user:
      name: roboshop
   - name: Create a directory if it does not exist
     ansible.builtin.file:
      path: /app
      state: directory
   

  
