- name : rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
    
    - name: configure yum erlang repos
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: configure yum rabbitmq repos
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
    
    - name: install rabbitmq
      ansible.builtin.dnf:
       name: rabbitmq-server
       state: present

    - name: Start and Enable rabbitmq service
      ansible.builtin.service:
         name: rabbitmq-server
         state: started
         enabled: yes

    - name: create rabbitmq user
      ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

    - name: set permissions
      ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
     
   
   
  