
- name: install redis component
  hosts: redis
  become: yes
  tasks:
  - name: install remi release
    ansible.builtin.dnf : # check pacakge will work not
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present
      disable_gpg_check: true
  
  