- name : web
  hosts: web
  become: yes
  tasks:
   - name: Install Mongodb
     ansible.builtin.package:
         name: mongodb-org
         state: present

   - name: Start and Enable Mongodb service
     ansible.builtin.service:
         name: mongod
         state: started
         enabled: yes
